apiVersion: argoproj.io/vialpha1
kind: Application I
metadata:
  name: apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/sehindemi-tech/K8-Production-Project.git'
    targetRevision: HEAD
    path: app-hub

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
  - CreateNamespace=true