apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-pv-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-pv-reader
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argo-cd