apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-app-hub
  labels:
    app: the-app-hub
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: the-app-hub
  template:
    metadata:
      labels:
        app: the-app-hub
    spec:
    containers:
      - name: the-app-hub
        image: moabukar/the-app-hub:22e0324
        ports:
        containerPort: 3000